export const DEFAULT_ROLE_PERMISSIONS = {
  admin: {
    task: {
      create: true,
      complete: true,
      reopen: true,
      reject: true,
      assign: true,
      restart: true,
      close: true,
      transfer: true,
      changePriority: true,
      changeStatus: true,
      comment: true,
      delete: true,
      extendDueDate: true,
    },
    bug: {
      create: true,
      fix: true,
      reopen: true,
      verify: true,
      close: true,
      transfer: true,
      changeSeverity: true,
      changeStatus: true,
      comment: true,
      delete: true,
      extendDueDate: true,
    },
    project: {
      create: true,
      delete: true,
    },
  },
  project_manager: {
    task: {
      create: true,
      complete: true,
      reopen: true,
      reject: true,
      assign: true,
      restart: true,
      close: true,
      transfer: true,
      changePriority: true,
      changeStatus: true,
      comment: true,
      delete: true,
      extendDueDate: true,
    },
    bug: {
      create: true,
      fix: true,
      reopen: true,
      verify: true,
      close: true,
      transfer: true,
      changeSeverity: true,
      changeStatus: true,
      comment: true,
      delete: true,
      extendDueDate: true,
    },
    project: {
      create: true,
      delete: false,
    },
  },
  developer: {
    task: {
      create: true,
      complete: false,
      reopen: false,
      reject: false,
      assign: false,
      restart: false,
      close: false,
      transfer: false,
      changePriority: false,
      changeStatus: false,
      comment: true,
      delete: false,
      extendDueDate: false,
    },
    bug: {
      create: true,
      fix: false,
      reopen: false,
      verify: false,
      close: false,
      transfer: false,
      changeSeverity: false,
      changeStatus: false,
      comment: true,
      delete: false,
      extendDueDate: false,
    },
    project: {
      create: false,
      delete: false,
    },
  },
  artist: {
    task: {
      create: true,
      complete: false,
      reopen: false,
      reject: false,
      assign: false,
      restart: false,
      close: false,
      transfer: false,
      changePriority: false,
      changeStatus: false,
      comment: true,
      delete: false,
      extendDueDate: false,
    },
    bug: {
      create: true,
      fix: false,
      reopen: false,
      verify: false,
      close: false,
      transfer: false,
      changeSeverity: false,
      changeStatus: false,
      comment: true,
      delete: false,
      extendDueDate: false,
    },
    project: {
      create: false,
      delete: false,
    },
  },
  designer: {
    task: {
      create: true,
      complete: false,
      reopen: false,
      reject: false,
      assign: false,
      restart: false,
      close: false,
      transfer: false,
      changePriority: false,
      changeStatus: false,
      comment: true,
      delete: false,
      extendDueDate: false,
    },
    bug: {
      create: true,
      fix: false,
      reopen: false,
      verify: false,
      close: false,
      transfer: false,
      changeSeverity: false,
      changeStatus: false,
      comment: true,
      delete: false,
      extendDueDate: false,
    },
    project: {
      create: false,
      delete: false,
    },
  },
  tester: {
    task: {
      create: true,
      complete: false,
      reopen: false,
      reject: false,
      assign: false,
      restart: false,
      close: false,
      transfer: false,
      changePriority: false,
      changeStatus: false,
      comment: true,
      delete: false,
      extendDueDate: false,
    },
    bug: {
      create: true,
      fix: false,
      reopen: false,
      verify: false,
      close: false,
      transfer: false,
      changeSeverity: false,
      changeStatus: false,
      comment: true,
      delete: false,
      extendDueDate: false,
    },
    project: {
      create: false,
      delete: false,
    },
  },
};

export const TASK_ACTION_LABELS: Record<string, string> = {
  create: "创建任务",
  complete: "完成",
  reopen: "重新打开",
  reject: "打回",
  assign: "指派",
  restart: "重启",
  close: "关闭",
  transfer: "转交",
  changePriority: "更改优先级",
  comment: "备注",
  delete: "删除",
};

export const BUG_ACTION_LABELS: Record<string, string> = {
  create: "创建BUG",
  fix: "已修复",
  reopen: "重新打开",
  verify: "验证通过",
  close: "关闭",
  assign: "分配",
  changeSeverity: "更改严重程度",
  comment: "备注",
  delete: "删除",
};

export const PROJECT_ACTION_LABELS: Record<string, string> = {
  create: "创建项目",
  delete: "删除项目",
};

export const ROLE_LABELS: Record<string, string> = {
  admin: "管理员",
  project_manager: "项目经理",
  developer: "程序",
  artist: "美术",
  designer: "策划",
  tester: "测试",
};
